name: Train ML Model

on: [push]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt

      - name: Run training script
        run: |
          python MLProject/modelling.py
